apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-demo.fullname" . }}-html
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
data:
  index.html: {{ .Values.htmlContent | quote }}
